### ISSUE TITLE
Noblocks: Switch networks

### ISSUE THREAD

**Issue by Shallysunny** [paycrest/zap#20]
**Issue Description**  
Implement a switch network/chains functionality on Noblocks to allow users to select and switch between different blockchain networks using a dropdown menu.

**Acceptance Criteria**

1. **GIVEN** the user is on Noblocks,  
   **WHEN** they open the network dropdown,  
   **THEN** they should be able to view a list of supported blockchain networks/chains (e.g., Ethereum, Binance Smart Chain, Polygon).

2. **GIVEN** the user selects a different network from the dropdown,  
   **WHEN** they confirm the selection,  
   **THEN** the application should switch to the selected network, updating the relevant settings and user interface.

**Tech Details:**

- Integrate a network switcher dropdown that allows users to switch between multiple blockchain networks.
- Ensure the network switching is seamless and updates the application to match the selected chain.
- Handle network-specific details such as chain IDs and RPC URLs to ensure proper network connections.

**Notes/Assumptions:**

- Users must already have a connected wallet, and the network switcher should work smoothly with supported wallets like MetaMask.
- Ensure the functionality works across different devices and browsers.

**Comment by jeremy0x** [comment]
moved to noblocks repo
