### ISSUE TITLE
Noblocks: Update Logo and Color on Existing Design

### ISSUE THREAD

**Issue by Shallysunny** [paycrest/zap#21]
**User Story**  
As a user, I want to see the updated logo and brand colors, so that the interface aligns with the latest branding guidelines.

**Acceptance Criteria**

1. **GIVEN** the existing design,  
   **WHEN** the logo is updated,  
   **THEN** the new logo should be reflected on all applicable pages (e.g., header, footer, and any other branded elements).

2. **GIVEN** the current color scheme,  
   **WHEN** the color palette is updated,  
   **THEN** the new colors should be applied across the interface according to the updated design guidelines.

3. **GIVEN** I am viewing the updated design,  
   **WHEN** I access it on mobile or desktop,  
   **THEN** the logo and colors should appear consistently across all devices and resolutions.

4. **GIVEN** the design update,  
   **WHEN** I interact with buttons, links, or other UI elements,  
   **THEN** the updated colors should apply to interactive states (e.g., hover, active, disabled).

**Product & Design Links:**

- [Updated Logo](#)
- [Updated Color Scheme](#)

**Tech Details:**

- Replace the old logo file with the new one across the app.
- Update the global color variables in the stylesheet to reflect the new palette.
- Ensure all logo placements and color changes are tested across all pages (responsive design and different screen sizes).
  
**Open Questions:**

- Are there any specific sections or pages that require unique branding updates?

**Notes/Assumptions:**

- The updated logo and colors are finalized and approved by the design team.
- Ensure no old branding elements remain after the update is applied.

**Comment by jeremy0x** [comment]
ticket completed in this commit: https://github.com/paycrest/zap/commit/7dd908f40f848bfec1b0ecd1108bd4dfb53fbbcf
