### ISSUE TITLE
Noblocks: "You're In" Screen for Successful Waitlist Signup

### ISSUE THREAD

**Issue by Shallysunny** [paycrest/zap#27]
**User Story**  
As a user, I want to see a confirmation screen after joining the waitlist, so that I know I have successfully signed up and can anticipate further communication.

**Acceptance Criteria**

1. **GIVEN** I have successfully joined the waitlist,  
   **WHEN** the submission is successful,  
   **THEN** I should be redirected to a "You're In" screen confirming my signup.

2. **GIVEN** I am on the "You're In" screen,  
   **WHEN** I view the page,  
   **THEN** I should see a success message and any additional details (e.g., "Thank you for joining the waitlist, we'll notify you soon").

**Product & Design Links:**

- [(https://www.figma.com/design/37OZ1Z9tj8SBTmvcLKHpMw/(NEW)-Paycrest?node-id=5821-241675&t=3KyRuDgVMZqrog9I-4)](#)
![Image](https://github.com/user-attachments/assets/00d92bd8-f397-4f3f-80b1-b9f427b5db86)

**Tech Details:**

- Show the confirmation screen upon successful submission of the waitlist form.
- Use the appropriate message and style (success modal or dedicated page) to indicate completion.
- Include an option to share the success on social platforms (optional but can increase engagement).
- Ensure this screen is mobile-friendly and optimized for performance.

**Open Questions:**

- Are there any follow-up actions we want the user to take after joining the waitlist (e.g., refer a friend)?

**Notes/Assumptions:**

- The backend should confirm waitlist signup success before displaying this screen.
- Ensure this screen is only shown when signup is 100% successful (no errors).

**Comment by jeremy0x** [comment]
completed here: https://github.com/paycrest/zap/commit/ea27d5d3ebbe85739c18af84ab0856a96a6a7a00
