### ISSUE TITLE
Add Noblocks Waitlist Banner

### ISSUE THREAD

**Issue by chibie** [paycrest/zap#34]
**User Story**
As a product manager, I want to add a banner on the Zap homepage to inform users about the Noblocks waitlist, as Zap was a hackathon project that is now being launched as Noblocks.

**Acceptance Criteria**
1. **GIVEN** a user visits the zap.paycrest.io,
  **WHEN** the page loads,
  **THEN** a prominent banner should be displayed, inviting them to join the Noblocks waitlist.

2. **GIVEN** the user clicks on the banner,
  **WHEN** they are redirected to the Noblocks waitlist,
  **THEN** they should be able to enter their email and join the waitlist.

3. **GIVEN** the Noblocks waitlist banner is added,
  **WHEN** the product team reviews the implementation,
  **THEN** the banner should be visually appealing, attention-grabbing, and consistent with the Noblocks branding.

4. **GIVEN** the banner is live,
  **WHEN** user signups are tracked,
  **THEN** we should see an increase in waitlist registrations from zap.paycrest.io visitors.

**Tech Details**
* Integrate banner click and signup tracking to measure performance
 
**Product & Design Links**
* Figma design: [TO BE PROVIDED]

**Notes/Assumptions**

**Open Questions**
1. Should the banner be displayed on all pages, or only on the homepage?
2. How can we ensure the banner doesn't negatively impact the user experience?

**Comment by doxabay** [comment]
Here is [the design](https://www.figma.com/design/37OZ1Z9tj8SBTmvcLKHpMw/Paycrest-Design?node-id=9687-116756&node-type=section&t=7BZGdcnYC0JCazlu-11)
