### ISSUE TITLE
Noblocks: Integrate Privy.io for Wallet Connection

### ISSUE THREAD

**Issue by Shallysunny** [paycrest/zap#7]
**User Story**  
As a developer, I want to integrate Privy.io for wallet connection, so that users can securely and seamlessly connect their wallets to our platform.

**Acceptance Criteria**

1. **GIVEN** the Privy.io SDK is integrated,  
   **WHEN** a user navigates to the wallet connection screen,  
   **THEN** they should be able to connect their wallet using the Privy.io service.

2. **GIVEN** a user initiates the wallet connection process,  
   **WHEN** the connection is successful,  
   **THEN** the user's wallet address should be securely linked to their account on our platform.

3. **GIVEN** the wallet connection is established,  
   **WHEN** the user refreshes or revisits the dashboard,  
   **THEN** their connected wallet should remain linked and active.

4. **GIVEN** an error occurs during the wallet connection process,  
   **WHEN** the error is encountered,  
   **THEN** a clear and actionable error message should be displayed to the user.

**Product & Design Links:**

- [Link to Wallet Connection Screen Design Mockup](#)
  
- [Privy Demo](https://demo.privy.io/)

**Tech Details:**

- Integrate the Privy.io SDK into the application for wallet connection.
- Ensure the wallet connection process is secure and user-friendly.
- Update backend services to handle and store the wallet connection data.
- Implement error handling to manage any issues during the wallet connection process.

**Notes/Assumptions:**

- Assume that the necessary API keys and configuration for Privy.io are already available.
- The integration should comply with the security standards required for handling sensitive wallet data.

**Comment by jeremy0x** [comment]
@Shallysunny the UI for this has been completed, what's only left is backend integration, you can update the title/description to show that.
